version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: org.reflections:reflections
    versions:
    - "> 0.9.11, < 0.10"
  - dependency-name: org.eclipse.jetty:jetty-webapp
    versions:
    - 11.0.0
    - 11.0.1
    - 11.0.2
  - dependency-name: org.eclipse.jetty:jetty-server
    versions:
    - 11.0.0
    - 11.0.1
    - 11.0.2
  - dependency-name: org.eclipse.jetty.websocket:websocket-client
    versions:
    - 9.4.36.v20210114
    - 9.4.37.v20210219
    - 9.4.38.v20210224
    - 9.4.39.v20210325
  - dependency-name: org.eclipse.jetty.websocket:websocket-server
    versions:
    - 9.4.36.v20210114
    - 9.4.37.v20210219
    - 9.4.38.v20210224
    - 9.4.39.v20210325
  - dependency-name: org.eclipse.jetty.websocket:websocket-api
    versions:
    - 9.4.36.v20210114
    - 9.4.37.v20210219
    - 9.4.38.v20210224
    - 9.4.39.v20210325
  - dependency-name: org.apache.logging.log4j:log4j-1.2-api
    versions:
    - 2.14.0
  - dependency-name: org.apache.logging.log4j:log4j-core
    versions:
    - 2.13.0
