name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: feature
body:
  - type: textarea
    attributes:
      label: Describe the Problem
      description: A clear and concise description of the problem you're facing.
      placeholder: |
        Ex. I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    attributes:
      label: The Solution you'd like
      description: A clear and concise description of the feature you would like added. The feature should be a way to solve the problem stated above.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alternatives that you've considered.
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, mockups about the feature request here.