name: Submit a Question
description: Technical Questions
title: '[Question]: '
labels: question
body:
  - type: markdown
    attributes:
      value: |
        *This should NOT be used for general questions on use of MapTool*
        For user support, please post your question on the Forums: http://forums.rptools.net
        Or on our Discord channel: [Invite Link](https://discord.gg/2FCwhZ9)
        Or on Reddit: [r/MapTool](https://www.reddit.com/r/MapTool/)
  - type: textarea
    attributes:
      label: Your Question
      description: A clear and concise question regarding this Fork, how to contribute, or similar topics.
    validations:
      required: true