= Converting MediaWiki Dump to MapTool Properties Help File

These scripts and auxiliary files are used to extract the documentation
from Craig's `wiki.rptools.info` website and store them here under the
`processed/` directory.

The MediaWiki software adds some boilerplate that is removed in these
files – we only keep the contents of `&lt;div id=&quot;mw-content-text&quot;&gt;` but
even that has pieces removed, like the table of contents and all
HTML comments.

The end result is a Java properties file that we can manually copy to
`../../src/main/resources/net/rptools/maptool/language/macro_descriptions/`
under the name `i18n.properties`.

== Conversion Process

=== `1-wiki-getfnnames.py &gt; wiki-has.txt`

This Python3 script reads Craig's MediaWiki dump file and makes a
list of all pages that appear to describe macro functions. This
list is stored in `wiki-has.txt` and is used in the next step.

=== `2-get-wiki-pages.sh`

This script reads the `wiki-has.txt` file to determine which pages
to retrieve. It grabs them using `wget` and puts them under the
`wiki.rptools.info` directory. The actual pages are under `index.php/`
and auxiliary files are under other subdirectories (like JavaScripts,
CSS, and images).

=== `3-extract-mw-content.sh`

This script extracts the proper `&lt;div&gt;` from the pages under
`wiki.rptools.info/index.php/`, checking to ensure the HTML is valid,
and then reformatting and re-indenting the document when
generating the output. That output is put under `processed/` for
use in the next step.

=== `4-generate-macro-list.sh`

// This Perl script is currently broken on my Mac, so I need to
// rewrite it in Python.  That reduces the reliance on another
// language as well, so probably for the better.

The output of this script should be redirected to `processed.txt`
as it becomes input for the next step.

This script reads the files under `processed/` and creates an
"index" that lists each filename and the description of the
macro that the file documents. It looks for `&lt;div
class=&quot;template_description&quot;&gt;` to isolate the description text.
This becomes input for the script in the next step.

=== `5-create-properties.sh`

The output of this script should be redirected to `i18n.properties`;
it is the final output from this process and should be copied to
`../../src/main/resources/net/rptools/maptool/language/macro_descriptions/`
after completion.

This script reads the index from the previous step, `processed.txt`,
and uses it to generate the `.description` records in the properties
file.

It also reads the HTML snippets stored under the
`processed/` directory to create the `.summary` records.

This script isn't perfect, as it doesn't always detect the `.description`
field properly. Future updates to the wiki pages may correct that.  (It
currently tries to grab the first "sentence", meaning a string of text
that ends with a period, question mark, or exclamation mark, followed by
at least one space.  Unfortunately, it can be confused by nested HTML
elements within that first sentence.)
